name: CI/CD Pipeline with DVC Auto Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write   # allow workflow to update repo contents
  packages: write   # allow pushing Docker images if needed

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found"
          pip install pytest dvc[all] mlflow dagshub scikit-learn pandas joblib

      # Step 4: Run tests (if you have any)
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q || echo "No tests found, skipping"

      # Step 5: Build Docker image (optional — if you want containerization)
      - name: Build Docker image
        run: |
          docker build -t my-mlops-app:latest .
        if: success()

  dvc-sync:
    runs-on: ubuntu-latest
    needs: build-and-test   # only run if build-and-test succeeds

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install DVC
      - name: Install DVC
        run: pip install dvc[all]

      # Step 4: Configure DVC remote (DagsHub shelves)
      - name: Configure DVC
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user ${{ secrets.DAGSHUB_USER }}
          dvc remote modify origin --local password ${{ secrets.DAGSHUB_TOKEN }}

      # Step 5: Push new data/models/metrics to DagsHub
      - name: DVC Push
        run: dvc push
